export const ADMIN_REQUEST="ADMIN_REQUEST";
export const ADMIN_FAILURE="ADMIN_FAILURE";
export const ADMIN_GET_PRODUCT="ADMIN_GET_PRODUCT";
export const ADMIN_POST_PRODUCT="ADMIN_GET_PRODUCT"
export const ADMIN_DELETE_PRODUCT="ADMIN_DELETE_PRODUCT";
export const ADMIN_PATCH_PRODUCT="ADMIN_PATCH_PRODUCT";
export const ADMIN_FILTER_PRODUCT="ADMIN_FILTER_PRODUCT";

export const GET_USER_DATA="GET_USER_DATA";
export const POST_USER_DATA="POST_USER_DATA";

export const GET_ORDER_DATA="GET_ORDER_DATA";
export const POST_ORDER_DATA="POST_ORDER_DATA";

export const ADD_CART_ITEM="ADD_CART_ITEM";
export const DELETE_CART_ITEM="DELETE_CART_ITEM";
export const RESET_CART_ITEM="RESET_CART_ITEM";

export const GET_ADMIN_DATA="GET_ADMIN_DATA";

